----
---
- name: HTTPD server is installed
  hosts: webdev
  vars:
    - web_package: httpd
    - web_service: httpd
    - web_config_file: /etc/httpd/conf/httpd.conf
    - web_root: /var/www/html/index.html
    - web_fw_service: http

  tasks:
    - name: Packages are installed
      ansible.builtin.dnf:
        name: "{{ web_package }}"
        state: present

    - name: Ensure service is started
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: started
        enabled: yes

    - name: Deploy configuration file
      ansible.builtin.template:
        src: templates/httpd.conf.j2
        dest: "{{ web_config_file }}"
        owner: root
        group: root
        mode: '0644'
        setype: httpd_config_t
      notify: restart httpd

    - name: Deploy index.html file
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{ web_root }}"
        owner: root
        group: root
        mode: '0644'

    - name: Web port is open
      ansible.builtin.firewalld:
        service: "{{ web_fw_service }}"
        permanent: yes
        state: enabled
        immediate: yes

  handlers:
    - name: restart httpd
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: restarted
