---
- name: Use the file module to remove a file
  hosts: all
  remote_user: root
  tasks:
    - name: Remove a file from managed hosts
      ansible.builtin.file:
        path: /home/devops/users.txt
        state: absent

