---
- name: Resolve host patterns
  hosts: db,&london
  gather_facts: no
  tasks:
  - name: Display managed hosts matching the host pattern
    ansible.builtin.debug:
      msg: "{{ inventory_hostname }}"

