---
- name: Display specific ansible_facts
  hosts: webserver
  tasks:
    - name: Display specific facts
      debug:
        msg: >
          Host "{{ ansible_facts['fqdn'] }}" with Python version "{{ ansible_facts['python_version'] }}" has "{{ ansible_facts['processor_count'] }}" processors and "{{ ansible_facts['memtotal_mb'] }}" MiB of total system memory.
